version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    expose:
      - "3000"
    networks:
      - front_end

  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    depends_on:
      - frontend
    volumes:
      - nginx_data:/data
      - nginx_letsencrypt:/etc/letsencrypt
    networks:
      - front_end

volumes:
  nginx_data:
    driver: local
  nginx_letsencrypt:
    driver: local
networks:
  front_end:
    driver: bridge
