version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"
    networks:
      - front_end

  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - nginx_data:/data
      - nginx_letsencrypt:/etc/letsencrypt
    depends_on:
      - backend
    networks:
      - dashboard_networks

volumes:
  nginx_data:
    driver: local
  nginx_letsencrypt:
    driver: local
networks:
  front_end:
    driver: bridge
