version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"
    networks:
      - front_end

  nginx:
    image: nginx:1.24-alpine-slim
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./infra/nginx/my_nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - front_end

networks:
  front_end:
    driver: bridge
