import type { Metadata } from 'next';

import { openSans, gothamPro } from '~fonts';
import styles from "./layout.module.scss";
import '~styles/index.scss';
import { Header, Footer } from '~widgets/index';


export const metadata: Metadata = {
  title: 'Загородный стиль',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className={`${openSans.variable} ${gothamPro.variable}`} lang="ru" >
      <body className={` ${styles.page}`}>
        <div className={styles.container} >
          <Header headerGridArea={styles.gridArea_header} />
            {children}
          <Footer footerGridArea={styles.gridArea_footer} />
        </div>
      </body>
    </html>
  );
}
